# The overall format is standard TOML format, v0.5.0.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[36,)" # This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for your mod.
license="MIT"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/ZandercraftGames/Door-Knocker-Forge/issues"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
# The modid of the mod
modId="doorknockerforge"
# The version number of the mod
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="${file.jarVersion}"
 # A display name for the mod
displayName="Door Knocker (Forge)"
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://github.com/ZandercraftGames/Door-Knocker-Forge"
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="icon.png"
# A text field displayed in the mod UI
credits="Thanks to MeowMC/FroyoCS for the original mod this is ported from."
# A text field displayed in the mod UI
authors="Zandercraft, FroyoCS"
# The description text for the mod
description='''
This mod adds a single feature; It allows you to left click on doors to knock on them.

This feature can really help role playing users as well as just be a nice thing to have when playing with friends.
'''
